### ISSUE TITLE
for course look into using hackmd for editing the docs

### ISSUE THREAD

**Issue by kjappelbaum** [cheminfo/eln.epfl.ch#215]

**Comment by kjappelbaum** [comment]
So, we can push/pull from hackmd 
<img width="714" alt="Screen Shot 2021-01-29 at 21 22 29" src="https://user-images.githubusercontent.com/32935233/106323727-287fe500-6278-11eb-9387-1e95108a0ec1.png">

but people would still need to create a GH account ... 

<img width="1000" alt="Screen Shot 2021-01-29 at 21 22 01" src="https://user-images.githubusercontent.com/32935233/106323760-39c8f180-6278-11eb-9912-5a4454e8f8d2.png">

**Comment by kjappelbaum** [comment]
and then anyhow you can only work on the repos you have access to. So we'd need them to 

- show how to create a GH account
- how to work a repo
- how to edit the markdown file (this can be done in hackmd)
- how to make a PR 

All of this is useful to know but we should probably should plan for an extra session where we show how this works. I can do this @lpatiny . Alternatively, we just ask for the tool they want to improve, send them the relevant files and they hand in the edited ones. But this requires much more manual work on our side. 

![Screen Shot 2021-01-29 at 21 26 48](https://user-images.githubusercontent.com/32935233/106324022-b4920c80-6278-11eb-8fb9-7e226470d041.png)

**Comment by lpatiny** [comment]
I wonder what is the best solution if it is teaching github / hackmd or to send them the files.

If they need to work with github account it could even be easier to teach them vscode with MD preview plugin.

Ideally we would need an (electron) application that simplifies all the tasks.  Maybe once we will find somebody that could develop this.

If we go to local editing (or creating an electron application) this project looks interesting https://marktext.app/

**Comment by kjappelbaum** [comment]
- the issue with sharing files is that we manually have to commit their edits which can be a mess
- the issue with an electron app is that one probably would still need a gh account such that the app can use the gh api to make a PR 


the cleanest version seems to me that they make a PR such that one can review/comment for the grading. a bit less clean is if we make a copy of the repo into the hackmd and share all files the students.

**Comment by lpatiny** [comment]
1. Create a github account
2. Fork the project on their account
3. Install vscode, git, MD preview plugin
4. Create a new branch
5. Edit the code and teach of to create correct screen snapshot
6. Difference between Tips and Readme
7. Commit
8. PR

**Comment by kjappelbaum** [comment]
Can you remind me what we wanted to say for 6?

**Comment by lpatiny** [comment]
If you look at the docs we have the possibility to write Tips. So there is the README.md that is displayed when you click on the question mark but you may also add an unlimited number of tips that are related to a revision of the view.

![image](https://user-images.githubusercontent.com/1484241/107187502-68686a00-69e6-11eb-8367-42553e0187b6.png)

This is for example an index.yml file in which we describe many tips
```yaml
description: Analyse polymers
uuid: 230d2530cee8782b3cb63dc4e25931d9
tips:
  - minRev: 1
    title: Interaction with mass spectrum
    name: spectrumDisplayer
  - minRev: 1
    title: Entering a molecular formula
    name: mf
  - minRev: 1
    title: Exporting results to a spreadsheet
    name: tableExport
  - minRev: 760
    title: Filtering using a function
    name: filteringFunction
```

A tip is associated with a folder name (`name`) that contains a file called `index.md`

So the students may improve the README.md file but also add more tips if they find it useful.
